name: Deploy to Cloudways via SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Debug connection (no secrets printed)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass
          REMOTE_DIR="${{ vars.CLOUDWAYS_REMOTE_PATH || secrets.CLOUDWAYS_REMOTE_PATH || 'public_html/site' }}"
          PORT="${{ vars.CLOUDWAYS_PORT || secrets.CLOUDWAYS_PORT || '22' }}"
          HOST="${{ vars.CLOUDWAYS_HOST || secrets.CLOUDWAYS_HOST || 'wordpress-1516217-5827651.cloudwaysapps.com' }}"
          USERNAME="${{ vars.CLOUDWAYS_USERNAME || secrets.CLOUDWAYS_USERNAME }}"
          PASSWORD="${{ vars.CLOUDWAYS_PASSWORD || secrets.CLOUDWAYS_PASSWORD }}"
          echo "Using host=$HOST port=$PORT user=$USERNAME remote=$REMOTE_DIR"
          sshpass -p "$PASSWORD" sftp -o StrictHostKeyChecking=no -P "$PORT" "$USERNAME@$HOST" -b /dev/null || true

      - name: Ensure remote directory exists via SFTP
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass
          REMOTE_DIR="${{ vars.CLOUDWAYS_REMOTE_PATH || secrets.CLOUDWAYS_REMOTE_PATH || 'public_html/site' }}"
          PORT="${{ vars.CLOUDWAYS_PORT || secrets.CLOUDWAYS_PORT || '22' }}"
          HOST="${{ vars.CLOUDWAYS_HOST || secrets.CLOUDWAYS_HOST || 'wordpress-1516217-5827651.cloudwaysapps.com' }}"
          USERNAME="${{ vars.CLOUDWAYS_USERNAME || secrets.CLOUDWAYS_USERNAME }}"
          PASSWORD="${{ vars.CLOUDWAYS_PASSWORD || secrets.CLOUDWAYS_PASSWORD }}"
          echo "Ensuring remote dir $REMOTE_DIR on $HOST:$PORT..."
          sshpass -p "$PASSWORD" sftp -o StrictHostKeyChecking=no -P "$PORT" "$USERNAME@$HOST" << EOF
            mkdir $REMOTE_DIR
            quit
EOF

      - name: Deploy build to Cloudways via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ vars.CLOUDWAYS_HOST || secrets.CLOUDWAYS_HOST || 'wordpress-1516217-5827651.cloudwaysapps.com' }}
          port: ${{ vars.CLOUDWAYS_PORT || secrets.CLOUDWAYS_PORT || '22' }}
          username: ${{ vars.CLOUDWAYS_USERNAME || secrets.CLOUDWAYS_USERNAME }}
          password: ${{ vars.CLOUDWAYS_PASSWORD || secrets.CLOUDWAYS_PASSWORD }}
          local_path: build/*
          remote_path: ${{ vars.CLOUDWAYS_REMOTE_PATH || secrets.CLOUDWAYS_REMOTE_PATH || 'public_html/site' }}
          sftp_only: true


